package com.example.unofficialsatisfactorymanuel

import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.unit.dp

val itemsName = listOf(
    "Adaptive Control Unit",
    "AI Expansion Server",
    "AI Limiter",
    "Alclad Aluminum Sheet",
    "Alien DNA Capsule",
    "Alien Power Matrix",
    "Alien Protein",
    "Alien Remains",
    "Aluminum Casing",
    "Aluminum Ingot",
    "Aluminum Scrap",
    "Assembly Director System",
    "Automated Wiring",
    "Bacon Agaric",
    "Ballistic Warp Drive",
    "Battery",
    "Bauxite",
    "Beacon",
    "Beryl Nut",
    "Biochemical Sculptor",
    "Biomass",
    "Black Powder",
    "Blade Runners",
    "Boom Box",
    "Cable",
    "Caterium Ingot",
    "Caterium Ore",
    "Chainsaw",
    "Circuit Board",
    "Coal",
    "Color Cartridge",
    "Compacted Coal",
    "Computer",
    "Concrete",
    "Cooling System",
    "Copper Ingot",
    "Copper Ore",
    "Copper Powder",
    "Copper Sheet",
    "Crude Oil",
    "Crystal Oscillator",
    "Cup",
    "Dark Matter Crystal",
    "Diamonds",
    "Electromagnetic Control Rod",
    "Empty Canister",
    "Empty Fluid Tank",
    "Encased Industrial Beam",
    "Encased Plutonium Cell",
    "Encased Uranium Cell",
    "Fabric",
    "FICSIT Coupon",
    "Ficsite Ingot",
    "Ficsite Trigon",
    "FICSMAS/Equipment",
    "Ficsonium",
    "Ficsonium Fuel Rod",
    "Flower Petals",
    "Fused Modular Frame",
    "Gas Mask",
    "Hard Drive",
    "Hazmat Suit",
    "Heat Sink",
    "Heavy Modular Frame",
    "High-Speed Connector",
    "Hoverpack",
    "HUB Parts",
    "Iron Ingot",
    "Iron Ore",
    "Iron Plate",
    "Iron Rod",
    "Jetpack",
    "Leaves",
    "Limestone",
    "Magnetic Field Generator",
    "Medicinal Inhaler",
    "Mercer Sphere",
    "Miner",
    "Modular Engine",
    "Modular Frame",
    "Motor",
    "Mycelia",
    "Neural-Quantum Processor",
    "Nobelisk Detonator",
    "Non-Fissile Uranium",
    "Nuclear Pasta",
    "Object Scanner",
    "Packaged Alumina Solution",
    "Packaged Fuel",
    "Packaged Heavy Oil Residue",
    "Packaged Ionized Fuel",
    "Packaged Liquid Biofuel",
    "Packaged Nitric Acid",
    "Packaged Nitrogen Gas",
    "Packaged Oil",
    "Packaged Rocket Fuel",
    "Packaged Sulfuric Acid",
    "Packaged Turbofuel",
    "Packaged Water",
    "Paleberry",
    "Parachute",
    "Petroleum Coke",
    "Plastic",
    "Plutonium Fuel Rod",
    "Plutonium Pellet",
    "Plutonium Waste",
    "Polymer Resin",
    "Power Shard",
    "Power Slug",
    "Pressure Conversion Cube",
    "Quartz Crystal",
    "Quickwire",
    "Radio Control Unit",
    "Raw Quartz",
    "Reanimated SAM",
    "Rebar Gun",
    "Reinforced Iron Plate",
    "Rifle",
    "Rotor",
    "Rubber",
    "SAM",
    "SAM Fluctuator",
    "Screw",
    "Silica",
    "Singularity Cell",
    "Smart Plating",
    "Smokeless Powder",
    "Solid Biofuel",
    "Somersloop",
    "Somersloop/zh",
    "Stator",
    "Statues",
    "Steel Beam",
    "Steel Ingot",
    "Steel Pipe",
    "Sulfur",
    "Supercomputer",
    "Superposition Oscillator",
    "Thermal Propulsion Rocket",
    "Time Crystal",
    "Turbo Motor",
    "Uranium",
    "Uranium Fuel Rod",
    "Uranium Waste",
    "Versatile Framework",
    "Vines",
    "Wire",
    "Wood",
    "Xeno-Basher",
    "Xeno-Zapper",
    "Ziplin"
)

@Composable
fun ItemsScreen(modifier: Modifier = Modifier) {
    val filteredItemsName = itemsName.map { it.substringBefore("/") }.distinct()
    Column(modifier = modifier.padding(16.dp)) {
        Text(text = "List of Items:")
        LazyColumn {
            items(filteredItemsName) { itemName ->
                Text(text = "- $itemName")
            }
        }
    }
}